// ReSharper disable All
namespace network.common
{
    public enum Protocol
    {
        C_TO_U_HEART_BEAT = 0,
        U_TO_C_HEART_BEAT,
        C_TO_U_LOGIN,
        U_TO_C_LOGIN,
        C_TO_U_SET_NAME,
        U_TO_C_SET_NAME,
        U_TO_C_INVENTORY_ITEM_LIST,
        U_TO_C_INVENTORY_UPDATE,
        C_TO_U_CHAT_MSG,
        U_TO_C_CHAT_MSG,
        C_TO_U_CHAT_LOG,
        U_TO_G_MOVE,
        G_TO_U_UPDATE_OBJECT,
        G_TO_U_SPAWN,
        G_TO_U_DESTROY,
        U_TO_C_MAP_UPDATE,
        C_TO_U_PLAYER_INFO,
        U_TO_C_PLAYER_INFO,
        G_TO_U_PLAYER_INFO,
        C_TO_U_OBJECT_INFO,
        C_TO_U_EXPLORE_TARGET_INFO,
        U_TO_C_EXPLORE_TARGET_INFO,
        G_TO_U_EXPLORE_TARGET_INFO,
        C_TO_U_EXPLORE,
        U_TO_C_EXPLORE,
        U_TO_C_EXPLORE_COMPLETE,
        C_TO_U_WEAR_ITEM,
        U_TO_C_WEAR_ITEM,
        C_TO_U_USE_ITEM,
        U_TO_C_USE_ITEM,
        C_TO_U_CHANGE_MAP,
        U_TO_C_CHANGE_MAP,
        U_TO_C_CHANGE_MAP_SUCCESS,
        C_TO_U_CHANGE_MAP_SUCCESS,
        G_TO_U_ENTER_INSTANCE_SUCCESS,
        C_TO_U_ENCAMP,
        C_TO_U_DECAMP,
        U_TO_C_CAMP_INFO,
        C_TO_U_CAMP_INFO,
        U_TO_C_UPDATE_HP,
        U_TO_C_ADD_SELL_ITEM,
        U_TO_C_DELETE_SELL_ITEM,
        C_TO_U_BUY_ITEM,
        U_TO_C_BUY_ITEM,
        U_TO_U_DUPLICATE,
        U_TO_G_LOGOUT,
        G_TO_U_SOCIAL_ACTION,
        U_TO_C_QUEST_LIST,
        C_TO_U_QUEST_INCREASE,
        U_TO_C_QUEST_UPDATE,
        C_TO_U_QUEST_SUCCESS,
        U_TO_C_QUEST_SUCCESS,
        C_TO_U_MAIL_LIST,
        U_TO_C_MAIL_LIST,
        C_TO_U_MAIL_RECEIVE,
        U_TO_C_MAIL_RECEIVE,
        C_TO_U_ITEM_PUT,
        U_TO_C_ITEM_PUT,
        G_TO_U_TAKE_DAMAGE,
        C_TO_U_MATCHING,
        U_TO_C_MATCHING,
        C_TO_U_MATCHING_CANCEL,
        U_TO_C_MATCHING_CANCEL,
        U_TO_C_MATCHING_SUCCESS,
        U_TO_C_MATCHING_FAILED,

        // GameServer 전용 프로토콜 (클라이언트 직접 연결)
        C_TO_G_CONNECT,          // 클라이언트 → GameServer 연결 인증
        G_TO_C_CONNECT_RESULT,   // GameServer → 클라이언트 연결 결과
        C_TO_G_MOVE,
        G_TO_C_MOVE,
        G_TO_C_SPAWN,
        G_TO_C_DESTROY,
        C_TO_G_ATTACK,
        G_TO_C_ATTACK,
        C_TO_G_INTERACT,
        G_TO_C_INTERACT,
        C_TO_G_SOCIAL_ACTION,
        G_TO_C_SOCIAL_ACTION,
        G_TO_C_TAKE_DAMAGE,
        G_TO_C_ENVIRONMENT,
        G_TO_C_GAME_TIME_WARNING,
        G_TO_C_GAME_END,

        END
    }

    public enum ErrorCode
    {
        SUCCESS = 0,
        ALREADY_HAS_JOB,
        ALREADY_ANOTHER_USE_SKILL,
        INVALID_POSITION,
        FATAL
    }
}
