<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.108"/>
    <PackageReference Include="MessagePackAnalyzer" Version="2.5.108"/>
    <PackageReference Include="MessagePack.ReactiveProperty" Version="2.5.108"/>
    <PackageReference Include="MessagePack.UnityShims" Version="2.5.108"/>
    <PackageReference Include="MessagePack.AspNetCoreMvcFormatter" Version="2.5.108"/>
  </ItemGroup>
</Project>
